### ISSUE TITLE
Error when doing 'pod install'

### ISSUE THREAD

**Issue by darkbrow** [tnantoka/edhita#13]
$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
Fetching podspec for `Megrim` from `https://raw.githubusercontent.com/tnantoka/podspecs/master/Specs/Megrim/Megrim.podspec`
[!] The `Megrim` pod failed to validate due to 3 errors:
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | description: The description is equal to the summary.
    - ERROR | description: The description is empty.
    - ERROR | File Patterns: The Megrim (0.1.0) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).

[!] Ignoring obsolete `HEAD` specifier in `EDHFontSelector (HEAD)`

[!] Ignoring obsolete HEAD specifier in `HEAD based on 0.2.1`

**Comment by tnantoka** [comment]
Thanks for the report. I fixed it.
