### ISSUE TITLE
Double-tapping "Delete" button crashes the app

### ISSUE THREAD

**Issue by ad510** [tnantoka/edhita#18]
If you double-tap the "Delete" button while the animation is still playing, it crashes the app and also deletes the most recent file in the directory in addition to the file you selected. (I keep backups, so I didn't lose any work from this. :smile:)

**Comment by ad510** [comment]
This is fixed for me as of version 2.0.5. Thanks!

**Comment by tnantoka** [comment]
@ad510 Thanks for the report 👍
